### ISSUE TITLE
failing tests

### ISSUE THREAD

**Issue by mjburton11** [convexengineering/turbofan#13] opened 2017-11-08 16:43 UTC
@1ozturkbe this repo is currently failing tests, :( looks like it's getting an unknown only on `macys` which is interesting, but we should still fix this.

**Comment by 1ozturkbe** [comment] 2017-11-08 18:48
@mjburton11 unfortunately this is not my area of expertise. @mayork?

**Comment by bqpd** [comment] 2017-11-10 20:21
We'll remove turbofan from tests next week if it isn't reliably passing :(

**Comment by mayork** [comment] 2017-11-10 20:30
@bqpd that seems a little extreme because I have never once been able to reproduce this error locally on my machine.

If someone can get the tests to fail on their computer then I would like to see that...but until then I think the testing architecture might need to be tweaked somehow

**Comment by mjburton11** [comment] 2017-11-10 20:33
That's fair, but it fails tests often enough that it blocks PR in gpkit and gplibrary, or once we push it fails and then it looks like all our repos are failing.

**Comment by mayork** [comment] 2017-11-10 20:39
It doesn't really matter if you drop it because it's implicitly tested in the SPaircraft model....but I really think it's strange that this sporadically fails. Does SPaircraft not have the same issue?

**Comment by mjburton11** [comment] 2017-11-10 20:39
It does but less frequently

**Comment by mayork** [comment] 2017-11-10 20:39
Interesting...

**Comment by mayork** [comment] 2017-11-10 20:40
I think there's some issue with the large SP models and how the tests are set up.

**Comment by mayork** [comment] 2017-11-10 20:40
I'm fine dropping the tests to improve work flow, but I think long term some deeper investigation into what's happening should be done. (I have tried but can't replicate the failure at all so I didn't get very far lol)

**Comment by bqpd** [comment] 2017-11-10 20:43
turbofan will still be on push/PR testing, and it's used as part of SPAircraft, so that'll be tested...but it looks like even turbofan_Push fails sometimes: https://acdl.mit.edu/csi/job/gpkit_ResearchModel_turbofan_Push/195/buildnode=windows7x64,optimizer=mosek/testReport/junit/gpkit.tests.from_paths/TestFiles/test_turbofan_engine_flight_profile_fleet_py_mosek/

It may only by `engine_flight_profile_fleet.py` that's the culprit? I don't think I've ever seen `engine_validation.py` fail...

**Comment by mayork** [comment] 2017-11-10 21:16
I took out the fleet test, lets see if that helps

**Comment by bqpd** [comment] 2017-11-13 01:58
so far so good!

**Comment by mayork** [comment] 2017-11-18 13:47
@bqpd @mjburton11 can we call this close this? If it's an issue again later on can always reopen.

**Comment by bqpd** [comment] 2017-11-18 14:10
Yup go for it!

**Closed** 2017-11-18 14:15 UTC
