### ISSUE TITLE
failing tests

### ISSUE THREAD

**Issue by whoburg** [convexengineering/turbofan#8] opened 2017-05-14 17:34 UTC
@mayork, do you know why this is failing tests? Can we get them passing reliably?

**Comment by mayork** [comment] 2017-05-14 17:41
not sure, I'll look into it. What's odd is it is only failing on some machines...

**Comment by whoburg** [comment] 2017-05-14 22:15
maybe the `test` method has fallen out of sync with what's in `__main__`? Those should probably rely on the same code

**Comment by mayork** [comment] 2017-05-15 13:57
resolved. test and main were out of sync slightly.

**Comment by bqpd** [comment] 2017-05-16 15:35
@mayork, @1ozturkbe, should we use __main__ instead of test?

**Comment by mayork** [comment] 2017-05-16 16:43
No I don't think so. This was just poorly formulated on my part. Fixed inD8.

**Comment by whoburg** [comment] 2017-06-21 14:25
tests are failing again.

**Comment by mayork** [comment] 2017-06-21 16:15
I haven't pushed to this in a while...odd...on vacation now I'll take a look in a few days.

**Comment by whoburg** [comment] 2017-07-03 15:13
status on this? Sporadic test failures are continuing.

**Comment by whoburg** [comment] 2017-07-03 16:18
@mayork and/or @1ozturkbe if one of you could prioritize this I'd appreciate it, I really want us to find it unacceptable when tests are failing. Makes us less likely to break things when improving GPkit.

**Comment by mayork** [comment] 2017-07-03 16:46
sorry had some family things come up and have had to take an unexpected trip to SC. I think I've narrowed it down to to two possible causes...the fix for once of which is just making a better testing framework within the turbofan repo, which I've started working on. Should be pushed soon.

**Comment by mayork** [comment] 2017-07-03 21:14
i made a series of updates that I think should have resolved this issue but it looks like there's now an import error within the model testing code on windows7x64... @bqpd what is going on here? The relevant output is at https://acdl.mit.edu/csi/job/gpkit_ResearchModel_turbofan_Push/buildnode=windows7x64,optimizer=mosek/125/console

**Comment by bqpd** [comment] 2017-07-03 21:29
re-running that test..seems to be hanging?

**Comment by mayork** [comment] 2017-07-03 21:36
it hung and eventually solved...i just made another push and got the exact same error

**Comment by bqpd** [comment] 2017-07-03 21:41
the new push seems to be failing on all moseks

**Comment by mayork** [comment] 2017-07-03 21:43
resolved that i'll see what happens on the current run

**Comment by mayork** [comment] 2017-07-03 21:46
hmm it's all passing now

**Comment by mayork** [comment] 2017-07-03 21:52
hmm well got 2 successful builds in a row. I'm going to close this for now, not sure what the import error was but it seems to have resolved itself. I think the turbofan tests should be much more stable now. I removed the possibility of having main and tests run with different substitutions.

**Comment by whoburg** [comment] 2017-07-07 17:02
Still failing

**Comment by mayork** [comment] 2017-07-07 18:46
@bqpd what are your thoughts on this. I'm not sure what to do because I cannot recreate any sort of failing behavior on my machine.

**Comment by bqpd** [comment] 2017-08-28 19:28
@mayork, this never fails on your machine?

**Comment by mayork** [comment] 2017-08-28 19:33
Nope! I almost think there's some issue with testing large SPs

**Comment by bqpd** [comment] 2017-08-28 20:09
hmm...across multiple platforms? I'll check if I can reproduce this failure & get back to you.

**Comment by mayork** [comment] 2017-08-28 20:23
For what's it worth I think the mosek failure is almost exclusively mosek_cli. Not sure why, seems like it shouldn't make a difference.

**Comment by bqpd** [comment] 2017-08-28 20:29
That's generally a sign of knife-edge...`mosek_cli` prints and reads floats from text files, causing some rounding.

**Comment by mayork** [comment] 2017-08-28 20:44
@bqpd I don't think it's knife edge...but....could the tex file rounding cause some issues for the signommial equalities? That is by far the least reliable constraint and is in both the engine and SP aircraft, the two places we are seeing this issue...

**Comment by bqpd** [comment] 2017-08-28 22:13
I guess 'knife edge' is a loaded word; I mean there's some effect where the program either converges to a good solution or to NEAR_OPTIMAL/UNKNOWN, and I think that the balance between those depends on very small effects (such as the text file rounding). Signomial Equalities seem more likely to have extreme approximations, so maybe?

**Comment by mayork** [comment] 2017-09-25 23:12
@1ozturkbe @bqpd did migrating the repo cause issues with the testing? I pushed to this repo and tests did not run.

**Comment by bqpd** [comment] 2017-09-26 03:58
I forgot to invite @acdl-jenkins to be an admin in the new org...once their invite is accepted, the webhooks should start working again.

**Comment by galbramc** [comment] 2017-09-26 13:48
@bqpd, I need to update the jenkins website it self to point to the new URL for this repo

**Comment by bqpd** [comment] 2017-09-26 14:11
ah, I thought I did that (for turbofan)

**Comment by galbramc** [comment] 2017-09-26 14:24
yeah I think you did, I just went through and updated everything else. We need a pull request in this repo to test it out though.

**Comment by galbramc** [comment] 2017-09-26 14:27
Looks like I can manually trigger the push test at least, but we need someone to push to the repo to be sure.

**Comment by mjburton11** [comment] 2017-10-13 21:39
@1ozturkbe @mayork or whoever is updating this repo, it is currently failing tests... :( gpkitmodels is now linked to integrated testing and I can't push my commit (convexengineering/library#121) because this is failing.

**Comment by mjburton11** [comment] 2017-10-15 03:11
@mayork @1ozturkbe can we please make this more reliable? gpkitmodels is setup on jenkins so every time we push this has to pass and it fails 2/3 of time and is very annoying.

**Comment by mayork** [comment] 2017-10-15 03:16
It's because mosek cli has some numerical instability. You can pull the code and run it 1000 times with mosek and it will work every time but the way mosek cli creates and passes mosek files causes sporadic failures. I think this is a testing architecture issue.

**Comment by galbramc** [comment] 2017-10-15 03:23
Are the files lacking precision for the cli printed with insufficient precision? Can you increase the digits in the floating point numbers?

**Comment by mjburton11** [comment] 2017-10-15 03:30
can you skip that solver?

**Comment by bqpd** [comment] 2017-10-15 04:15
(you can definitely just add that to skipsolvers in TESTCONFIG)

**Comment by mayork** [comment] 2017-10-15 04:56
Marshall yes to you and Ned I'll just do that

**Closed** 2017-10-16 16:59 UTC
